services:
  server:
    build:
      context: .
    environment:
      DB_HOSTNAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
        - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
