name: Python Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.7
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add project root to PYTHONPATH
        run: |
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Run tests
        run: |
          pytest .
